retrieve_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    The list of 10 websites with the most relevant information about {topic}
  agent: retrieve_news

website_scraper_task:
  description: >
    Scrape the website for the latest news and information.
  expected_output: >
    Fully scraped websites with all the important information from the website.
  agent: website_scraper

ai_news_writer_task:
  description: >
    Summarize the information from the websites into a full markdown news article.
  expected_output: >
    A markdown-formatted article summarizing all relevant news, without code fences (no ```).
  agent: ai_news_writer

file_writer_task:
  description: >
    Save the generated news article into a markdown file.
  expected_output: >
    A saved markdown file containing the AI-generated news article.
  agent: file_writer
  params:
    output_file: "ai_news_report.md"
